blockGatheringSpots: []
#  - boundingBox:
#      world: OVERWORLD
#      minimumCorner:
#        x: 0
#        y: 0
#        z: 0
#      maximumCorner:
#        x: 0
#        y: 0
#        z: 0
#    blockType: STONE
#    cooldownType: BEDROCK
#    drop:
#      type: STONE
#      name: Stone
#    cooldownInSeconds: 10

entityGatheringSpots: []
#  - spawnLocation:
#      world: OVERWORLD
#      x: 0
#      y: 0
#      z: 0
#    spawnRadius: 5
#    entityType: PIG
#    entityCount: 10
#    drop:
#      type: PORKCHOP
#      name: Meat
#    cooldownInSeconds: 10
