# CONFIGURATION
# Options: [LOCAL, REMOTE]
# ------------------------------------------------------------
# If set to LOCAL the Gathering plugin will only consider this
# config file for its configuration. Even if your Monolith
# configuration is set to use a non-LOCAL configuration service.
# If set to REMOTE the Gathering plugin will consider this
# config file for its meta-configuration (everything above the
# uppercase separator in the middle of the file) and will
# attempt to retrieve a remote file for the remainder of its
# configuration.
# If Monolith itself is configured to use LOCAL configuration
# or retrieving the REMOTE file fails it will fallback to
# LOCAL and use this file for all of its configuration.
configurationType: LOCAL

# The following value only matters if you are configuring a
# REMOTE configuration and will be ignored otherwise. This
# value should be the file name relative to the root of your
# remote configuration service store and contain all of the
# configuration below the uppercase separator in the middle
# of this file.
configurationFileName: relative/path/to/config.yml


# ------------------------------------------------------------
# ALL CONFIGURATION ABOVE THIS LINE HAS TO BE DONE LOCALLY

# ALL CONFIGURATION BELOW THIS LINE IS ELIGIBLE FOR REMOTE
# ------------------------------------------------------------


# GATHERING SPOTS
# World options: [OVERWORLD, THE_NETHER, THE_END]
# BlockType options: http://warcraft.gg/blocktypes
# CooldownType options: http://warcraft.gg/blocktypes
# DropType options: http://warcraft.gg/blocktypes
# ------------------------------------------------------------
#
blockGatheringSpots:
  - minimumCorner:
      world: OVERWORLD
      x: 0
      y: 0
      z: 0
    maximumCorner:
      world: OVERWORLD
      x: 0
      y: 0
      z: 0
    blockTypes: [STONE]
    cooldownType: BEDROCK
    drops:
      type: STONE
      name: Stone
    cooldownInSeconds: 10

entityGatheringSpots:
  - minimumCorner:
      world: OVERWORLD
      x: 0
      y: 0
      z: 0
    maximumCorner:
      world: OVERWORLD
      x: 0
      y: 0
      z: 0
    entityType: PIG
    entityCount: 10
    spawnLocation:
      world: OVERWORLD
      x: 0
      y: 0
      z: 0
      spawnRadius: 5
    drops:
      type: PORKCHOP
      name: Meat
    cooldownInSeconds: 10
