name: "WarCraft: Gathering"
version: 1.0.0
author: fishb6nes
authors: [fishb6nes, Chau]
website: http://warcraft.gg

main: gg.warcraft.gathering.spigot.GatheringPlugin
depend: ["WarCraft: Monolith"]

commands: []
